services:
  web:
    build: .
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: